language: julia

dist: xenial
services: 
  - xvfb

os:
  - linux
  - osx

julia:
  - 1.3
  - nightly
    
matrix:
  allow_failures:
    julia: nightly

cache:
    directories:
      - /home/travis/.julia/artifacts

notifications:
    email: false
